name: dartness

command:
  bootstrap:
    usePubspecOverrides: true

packages:
  - packages/**


scripts:
  get: melos exec --no-private -- dart pub get .
  analyze: melos exec --no-private -- dart analyze
  upgrade: melos exec --no-private -- dart pub upgrade --major-versions

  format: melos exec --no-private -- dart format .
  format:check: dart format --set-exit-if-changed .

  test: melos exec --dir-exists=test --no-private -- dart test

  pub:upgrade: melos exec --no-flutter -- dart pub upgrade

  doc: melos exec --no-private -- dart doc .

  publish:force: dart pub publish -f