name: dartness_server
description: Dartness root pubspec
version: 1.0.0
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  melos: ^3.1.0
