name: dartness_server
description:
  Dartness is a framework for building efficient, scalable dart server-side applications.
  It provides an easy and quick way to develop modern standalone server.
version: 0.2.0-alpha
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

false_secrets:
  - example/**

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  logger: ^1.1.0
  shelf: ^1.3.1
  shelf_plus: ^1.4.0
  shelf_router: ^1.1.3

dev_dependencies:
  http: ^0.13.4
  lints: ^2.0.0
  test: ^1.21.2
