name: dartness
description: Dartness is a framework for building efficient, scalable dart server-side applications. It provides an easy and quick way to develop modern standalone server.
version: 0.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  collection: ^1.16.0
  shelf: ^1.3.1
  shelf_router: ^1.1.3

dev_dependencies:
  coverage: ^1.3.2
  http: ^0.13.4
  lints: ^2.0.0
  test: ^1.21.2
