name: my_server
description: A sample dartness server.
version: 1.0.0
# homepage: https://www.example.com

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartness_server: ^0.4.6-alpha

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
  build_runner: ^2.4.6
  dartness_generator: ^0.1.3-alpha
