name: my_server
description: A sample dartness server.
version: 1.0.0
# homepage: https://www.example.com

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartness_server: ^0.7.0
  dio: ^5.3.3
  my_common:
    path: ../../commons

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
  build_runner: ^2.4.6
  dartness_generator: ^0.7.0
