name: my_common
description: A sample dartness server.
version: 1.0.0
# homepage: https://www.example.com

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
