name: dartness_server
description:
  Dartness is a framework for building efficient, scalable dart server-side applications.
  It provides an easy and quick way to develop modern standalone server.
version: 0.7.0
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

false_secrets:
  - examples/**

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  shelf: ^1.4.1
  shelf_plus: ^1.9.2
  shelf_router: ^1.1.4
  cron: ^0.6.0

dev_dependencies:
  http: ^1.2.1
  lints: ^4.0.0
  test: ^1.25.7
  build_runner: ^2.4.11
