name: dartness_server
description:
  Dartness is a framework for building efficient, scalable dart server-side applications.
  It provides an easy and quick way to develop modern standalone server.
version: 0.4.5-alpha
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

false_secrets:
  - examples/**

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  shelf: ^1.4.1
  shelf_plus: ^1.7.0
  shelf_router: ^1.1.4
  injector: ^3.0.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.1
  test: ^1.24.4
  build_runner: ^2.4.6
  dartness_generator:
    path: ../dartness_generator