name: example
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dartness_server: ^0.4.2-alpha

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
  build_runner: ^2.4.5
  dartness_generator: ^0.1.0-alpha
