name: dartness_simple
description: A sample dartness application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  dartness_server: ^0.2.0-alpha

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
