name: dartness_generator
description: Dartness generator provides the generator classes that are used to run dartness_server
version: 0.5.2-alpha
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.3.0
  code_builder: ^4.7.0
  graphs: ^2.3.1
  dartness_server: ^0.5.1-alpha

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.6
  test: ^1.24.9
  source_gen_test: ^1.0.6
