name: dartness_generator
description: Dartness generator provides the generator classes that are used to run dartness_server
version: 0.7.1
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  build: ^2.4.1
  source_gen: ^1.5.0
  analyzer: ^6.5.0
  code_builder: ^4.10.0
  dartness_server: ^0.7.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.11
  test: ^1.25.7
  source_gen_test: ^1.0.6
