name: dartness_generator
description: Dartness generator provides the generator classes that are used to run dartness_server
version: 0.1.1-alpha
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.2
  analyzer: ^5.13.0
  code_builder: ^4.5.0
  dartness_server: 0.4.3-alpha

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.5
  test: ^1.24.3
