name: dartness_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

# TODO temporal, remove when dartness_server is published
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.6.0
  code_builder: ^4.2.0
  # TODO change it to remote
  dartness_server:
    path: ../dartness_server/

dev_dependencies:
  lints: ^2.0.0
  build_test: ^2.1.5
  build_runner: ^2.2.0
  test: ^1.21.4
