name: dartness_generator
description: Dartness generator provides the generator classes that are used to run dartness_server
version: 0.1.0-alpha
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^4.6.0
  code_builder: ^4.2.0
  dartness_server: ^0.41-alpha

dev_dependencies:
  lints: ^2.0.0
  build_test: ^2.1.5
  build_runner: ^2.2.0
  test: ^1.21.4
