name: dartness_generator
description: Dartness generator provides the generator classes that are used to run dartness_server
version: 0.4.6-alpha
homepage: https://ricardorb.github.io/dartness/
repository: https://github.com/RicardoRB/dartness
issue_tracker: https://github.com/RicardoRB/dartness/issues
documentation: https://ricardorb.github.io/dartness/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.0.0
  code_builder: ^4.5.0
  dartness_server:
    path: ../dartness_server

dev_dependencies:
  lints: ^2.1.1
  build_runner: ^2.4.6
  test: ^1.24.4
  source_gen_test: ^1.0.6
