name: Dartness github actions

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos

      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: "Getting Dependencies"
        run: melos get

      - name: "Run Format"
        run: melos format

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos

      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: "Getting Dependencies"
        run: melos get

      - name: "Run Analyze"
        run: melos analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos

      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: "Getting Dependencies"
        run: melos get

      - name: "Run Test"
        run: melos test
