name: master

on:
  push:
    branches:
      - master

jobs:


  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh

      - name: "Bootstrap Workspace"
        run: melos bootstrap

      - name: "Getting Dependencies"
        run: melos pub:get

      - name: "Run Analyze"
        run: melos run analyze

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh

      - name: "Bootstrap Workspace"
        run: melos bootstrap

      - name: "Getting Dependencies"
        run: melos pub:get

      - name: "Run Format"
        run: melos run format:check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh

      - name: "Bootstrap Workspace"
        run: melos bootstrap

      - name: "Getting Dependencies"
        run: melos pub:get

      - name: Test
        run: melos run test

  publish:
    runs-on: ubuntu-latest
    needs: [ analyze, format, test ]
    steps:
      - name: Checkout pub publisher
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true