name: master

on:
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos

      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: "Getting Dependencies"
        run: melos get

      - name: "Run Format"
        run: melos format

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos

      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: "Getting Dependencies"
        run: melos get

      - name: "Run Analyze"
        run: melos analyze

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos

      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: "Getting Dependencies"
        run: melos get

      - name: "Run Test"
        run: melos test

  publish:
    runs-on: ubuntu-latest
    needs: [ analyze, format, test ]
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup credentials
        run: |
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1659717556326
          }
          EOF
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: "Install Melos"
        run: dart pub global activate melos
      - name: "Bootstrap Workspace"
        run: melos bootstrap --no-private

      - name: Publish package
        run: melos publish:force